language: node_js

node_js:
  - stable
cache: yarn

install:
  - yarn
before_script:
  - yarn danger ci
script:
  - yarn test --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  edge: true
  on:
    branch: master
